---
name: pre-commit

on:
  pull_request:
    branches:
      - 'master'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Oracle Cloud Infrastructure CLI
        run: |
          mkdir -p /home/runner/.oci/
          echo "${{ secrets.OCI_API_KEY }}" > /home/runner/.oci/oci_api_key.pem
          echo "${{ secrets.OCI_CONFIG }}" > /home/runner/.oci/config
          chmod 600 /home/runner/.oci/oci_api_key.pem
          chmod 600 /home/runner/.oci/config

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install terraform-docs
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TERRAFORM_DOCS_URL=$(curl -sL --header "Authorization: Bearer ${GH_TOKEN}" \
            https://api.github.com/repos/terraform-docs/terraform-docs/releases/latest \
            | grep browser_download_url | grep -o -E "https://.+?-linux-amd64.tar.gz")
          sudo wget -q -O /tmp/terraform-docs.tar.gz "$TERRAFORM_DOCS_URL"
          sudo tar -xzf /tmp/terraform-docs.tar.gz -C /usr/local/bin terraform-docs
          sudo chmod +x /usr/local/bin/terraform-docs

      - name: Install tflint
        uses: terraform-linters/setup-tflint@v4

      - name: Run pre-commit action
        uses: pre-commit/action@v3.0.1
